name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      description: What problem does this feature solve?
      placeholder: Ex. I want to be able to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature implemented?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you’ve thought about?